// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Dotnet7.Models

{
    public partial class TestContext : DbContext
    {
        public TestContext(DbContextOptions<DbContext> options)
        {
        }

        public TestContext(DbContextOptions<TestContext> options)
            : base(options)
        {
        }

        //public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //modelBuilder.Entity<Order>(entity =>
            //{
            //    entity.Property(e => e.OrderId).ValueGeneratedOnAdd();
            //});

            modelBuilder.Entity<Product>(entity =>
            {
                //entity.HasKey();
                entity.Property(e => e.ProductId).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Customer>(entity =>
            {
                //entity.HasKey();
                entity.Property(e => e.CustomerId).ValueGeneratedOnAdd();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}